name: Publish

on:
  workflow_run:
    workflows:
      - Linters
    types:
      - completed

permissions:
  contents: write   # required for creating a release

jobs:

  publish:
    runs-on: ubuntu-latest
    environment: prod
    name: Publish to Prod
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      # echo "REL_VER=poetry version --short" >> $GITHUB_ENV

    - name: Build package
      run: poetry build
    

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    # - name: Create release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "dist/*"
    #     tag: ${{ env.REL_VER }}


